# A linha 'version' pode ser removida, é obsoleta.
services:
  # Fila de Mensagens com Healthcheck
  redis:
    image: redis:alpine
    container_name: ianorth_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Banco de Dados com Healthcheck
  db:
    image: postgres:13
    container_name: ianorth_db
    env_file:
      - ./ianorth-api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gateway da API que espera os Healthchecks
  gateway:
    build:
      context: ./ianorth-api
      dockerfile: Dockerfile.gateway
    container_name: ianorth_gateway
    env_file:
      - ./ianorth-api/.env
    ports:
      - "8898:8898"
    depends_on:
      db:
        condition: service_healthy # <-- MÁGICA ACONTECE AQUI
      redis:
        condition: service_healthy # <-- E AQUI
    restart: unless-stopped

  # Worker que espera o Healthcheck do Redis
  worker_cam_patio_1:
    build:
      context: ./ianorth-api
      dockerfile: Dockerfile.worker
    container_name: worker_cam_patio_1
    env_file:
      - ./ianorth-api/.env
    depends_on:
      redis:
        condition: service_healthy # <-- E AQUI
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data:
