services:
  redis:
    image: redis:alpine
    container_name: ianorth_redis
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: ianorth_db
    env_file:
      - ./ianorth-api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  gateway:
    build:
      context: ./ianorth-api
      dockerfile: Dockerfile.gateway
    container_name: ianorth_gateway
    env_file:
      - ./ianorth-api/.env
    ports:
      - "8898:8898"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker_dev:
    build:
      context: ./ianorth-api
      dockerfile: Dockerfile.worker.dev
    container_name: worker_dev_m1
    env_file:
      - ./ianorth-api/.env
    depends_on:
      - redis
    restart: unless-stopped

  worker_cam_patio_1:
    build:
      context: ./ianorth-api
      dockerfile: Dockerfile.worker
    container_name: worker_cam_patio_1
    env_file:
      - ./ianorth-api/.env
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data:

